package com.example.im.mapper;

import com.example.im.model.Likes;
import com.example.im.model.Post;
import com.example.im.model.User;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface PostMapper {

    @Insert("insert into post(user_id,content,time,image) values(#{user_id},#{content},#{time},#{image})")
    int insertPost(Post post);

    @Select("select * from post order by time desc")//post_id, user_id, content, time, image
    List<Post> getPostList();

    @Insert("insert into likes(user_id, post_id, like_time) values(#{user_id}, #{post_id}, #{like_time})")
    int insertLikes(Likes likes);

    @Delete("delete from likes where post_id = #{post_id} and user_id = #{user_id}")
    int deleteLikes(Likes likes);

    @Select("select * from likes where post_id = #{post_id} order by like_time desc")//post_id, user_id, content, time, image
    List<Likes> getLikesListByPostId(int post_id);

    @Delete("delete from post where post_id = #{post_id}")
    int deletePost(int post_id);

    @Delete("delete from likes where post_id = #{post_id}")
    int deleteLikesByPostId(int post_id);

    @Update("update post set content = #{content}, image = #{image}, time = #{time} where post_id= #{post_id}")
    int updatePost(Post post);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    Post selectByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Post record);
}